{/* <EditorProvider>
    <div className="d-grid text-container">
        <div className="text-typography d-flex">
            <button onClick={Bold}>
                <span className={isBold ? 'active' : ''} id='bold'><b> B </b></span>
            </button>
            <button onClick={Italics}>
                <span className={isItalic ? 'active' : ''} id='italics'><i> i </i></span>
            </button>
            <button>
                <span className="attachment">
                    <svg className="attachment" width="20" height="15" viewBox="0 0 20 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M18.2813 1.225C17.9329 0.875397 17.5189 0.598009 17.0631 0.408738C16.6073 0.219468 16.1186 0.12204 15.625 0.12204C15.1315 0.12204 14.6428 0.219468 14.187 0.408738C13.7312 0.598009 13.3172 0.875397 12.9688 1.225L13.8563 2.1125C14.089 1.87981 14.3652 1.69523 14.6692 1.56931C14.9733 1.44338 15.2991 1.37856 15.6282 1.37856C15.9572 1.37856 16.2831 1.44338 16.5871 1.56931C16.8911 1.69523 17.1674 1.87981 17.4 2.1125C17.6327 2.34518 17.8173 2.62142 17.9432 2.92544C18.0692 3.22946 18.134 3.5553 18.134 3.88437C18.134 4.21344 18.0692 4.53928 17.9432 4.8433C17.8173 5.14732 17.6327 5.42356 17.4 5.65625L12.4 10.6562C11.9309 11.1262 11.2944 11.3905 10.6304 11.3911C9.96638 11.3917 9.32935 11.1285 8.85942 10.6594C8.38949 10.1903 8.12515 9.5537 8.12457 8.8897C8.12398 8.22571 8.38719 7.58868 8.85629 7.11875L9.73754 6.23125L8.85629 5.34375L7.96879 6.23125C7.61919 6.57963 7.3418 6.99361 7.15253 7.44943C6.96326 7.90524 6.86583 8.39394 6.86583 8.8875C6.86583 9.38105 6.96326 9.86975 7.15253 10.3256C7.3418 10.7814 7.61919 11.1954 7.96879 11.5437C8.67597 12.2419 9.63134 12.6308 10.625 12.625C11.1205 12.627 11.6114 12.5309 12.0695 12.3421C12.5276 12.1533 12.9437 11.8756 13.2938 11.525L18.2938 6.525C18.9944 5.82021 19.3866 4.86616 19.3842 3.87241C19.3819 2.87866 18.9852 1.92647 18.2813 1.225Z" fill="#212529"></path><path d="M2.61879 12.5125C2.38541 12.2802 2.20022 12.0041 2.07386 11.7C1.94749 11.3959 1.88244 11.0699 1.88244 10.7406C1.88244 10.4113 1.94749 10.0853 2.07386 9.78123C2.20022 9.47715 2.38541 9.20104 2.61879 8.96875L7.61879 3.96875C7.85109 3.73537 8.1272 3.55018 8.43127 3.42381C8.73534 3.29745 9.06138 3.2324 9.39067 3.2324C9.71995 3.2324 10.046 3.29745 10.3501 3.42381C10.6541 3.55018 10.9302 3.73537 11.1625 3.96875C11.3944 4.20287 11.577 4.48116 11.6994 4.78713C11.8218 5.0931 11.8815 5.42052 11.875 5.75C11.8769 6.0805 11.8133 6.4081 11.6878 6.71385C11.5623 7.01959 11.3774 7.29742 11.1438 7.53125L9.81879 8.875L10.7063 9.7625L12.0313 8.4375C12.7366 7.73219 13.1328 6.77558 13.1328 5.77812C13.1328 4.78066 12.7366 3.82406 12.0313 3.11875C11.326 2.41344 10.3694 2.0172 9.37192 2.0172C8.37446 2.0172 7.41785 2.41344 6.71254 3.11875L1.71254 8.11875C1.362 8.46725 1.08382 8.88161 0.893994 9.33801C0.704168 9.7944 0.606445 10.2838 0.606445 10.7781C0.606445 11.2724 0.704168 11.7618 0.893994 12.2182C1.08382 12.6746 1.362 13.089 1.71254 13.4375C2.42431 14.1303 3.38185 14.5124 4.37504 14.5C5.37698 14.501 6.33862 14.1055 7.05004 13.4L6.16254 12.5125C5.93025 12.7459 5.65413 12.9311 5.35006 13.0574C5.04599 13.1838 4.71995 13.2488 4.39067 13.2488C4.06138 13.2488 3.73534 13.1838 3.43127 13.0574C3.1272 12.9311 2.85109 12.7459 2.61879 12.5125Z" fill="#212529"></path></svg>
                </span>
            </button>
            <button>
                <span className="emoji" onClick={toggleEmojiPicker}>
                    <svg className="emoji" values='emoji' width="16" height="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0m0 22C6.486 22 2 17.514 2 12S6.486 2 12 2s10 4.486 10 10-4.486 10-10 10"></path><path d="M8 7a2 2 0 1 0-.001 3.999A2 2 0 0 0 8 7M16 7a2 2 0 1 0-.001 3.999A2 2 0 0 0 16 7M15.232 15c-.693 1.195-1.87 2-3.349 2-1.477 0-2.655-.805-3.347-2H15m3-2H6a6 6 0 1 0 12 0"></path></svg>
                </span>
            </button>
            {showEmoji && (
                <div className="emoji-picker">
                    <span onClick={() => addEmoji('😀')}>😀</span>
                    <span onClick={() => addEmoji('😃')}>😃</span>
                    <span onClick={() => addEmoji('😄')}>😄</span>
                    <span onClick={() => addEmoji('😁')}>😁</span>
                    <span onClick={() => addEmoji('😆')}>😆</span>
                    <span onClick={() => addEmoji('😅')}>😅</span>
                    <span onClick={() => addEmoji('😂')}>😂</span>
                    <span onClick={() => addEmoji('🤣')}>🤣</span>
                    <span onClick={() => addEmoji('🥲')}>🥲</span>
                    <span onClick={() => addEmoji('🥹')}>🥹</span>
                    <span onClick={() => addEmoji('😉')}>😉</span>
                    <span onClick={() => addEmoji('😊')}>😊</span>
                    <span onClick={() => addEmoji('😇')}>😇</span>
                    <span onClick={() => addEmoji('🙂')}>🙂</span>
                    <span onClick={() => addEmoji('🙃')}>🙃</span>
                    <span onClick={() => addEmoji('😌')}>😌</span>
                    <span onClick={() => addEmoji('😍')}>😍</span>
                    <span onClick={() => addEmoji('🥰')}>🥰</span>
                    <span onClick={() => addEmoji('😘')}>😘</span>
                    <span onClick={() => addEmoji('😗')}>😗</span>
                    <span onClick={() => addEmoji('😙')}>😙</span>
                    <span onClick={() => addEmoji('😚')}>😚</span>
                    <span onClick={() => addEmoji('😋')}>😋</span>
                    <span onClick={() => addEmoji('😛')}>😛</span>
                    <span onClick={() => addEmoji('😝')}>😝</span>
                    <span onClick={() => addEmoji('😜')}>😜</span>
                    <span onClick={() => addEmoji('🤪')}>🤪</span>
                    <span onClick={() => addEmoji('🤨')}>🤨</span>
                    <span onClick={() => addEmoji('🧐')}>🧐</span>
                    <span onClick={() => addEmoji('🤓')}>🤓</span>
                    <span onClick={() => addEmoji('😎')}>😎</span>
                    <span onClick={() => addEmoji('🥸')}>🥸</span>
                    <span onClick={() => addEmoji('🤩')}>🤩</span>
                    <span onClick={() => addEmoji('🥳')}>🥳</span>
                    <span onClick={() => addEmoji('🙂')}>🙂</span>
                    <span onClick={() => addEmoji('😏')}>😏</span>
                    <span onClick={() => addEmoji('😒')}>😒</span>
                    <span onClick={() => addEmoji('🙂')}>🙂</span>
                    <span onClick={() => addEmoji('😞')}>😞</span>
                    <span onClick={() => addEmoji('😔')}>😔</span>
                    <span onClick={() => addEmoji('😟')}>😟</span>
                    <span onClick={() => addEmoji('😕')}>😕</span>
                    <span onClick={() => addEmoji('🙁')}>🙁</span>
                    <span onClick={() => addEmoji('☹️')}>☹️</span>
                    <span onClick={() => addEmoji('😣')}>😣</span>
                    <span onClick={() => addEmoji('😖')}>😖</span>
                    <span onClick={() => addEmoji('😫')}>😫</span>
                    <span onClick={() => addEmoji('😩')}>😩</span>
                    <span onClick={() => addEmoji('🥺')}>🥺</span>
                    <span onClick={() => addEmoji('😢')}>😢</span>
                    <span onClick={() => addEmoji('😭')}>😭</span>
                    <span onClick={() => addEmoji('😮')}>😮</span>
                    <span onClick={() => addEmoji('😤')}>😤</span>
                    <span onClick={() => addEmoji('😠')}>😠</span>
                    <span onClick={() => addEmoji('😡')}>😡</span>
                    <span onClick={() => addEmoji('🤬')}>🤬</span>
                    <span onClick={() => addEmoji('🤯')}>🤯</span>
                    <span onClick={() => addEmoji('😳')}>😳</span>
                    <span onClick={() => addEmoji('🥵')}>🥵</span>
                    <span onClick={() => addEmoji('🥶')}>🥶</span>
                    <span onClick={() => addEmoji('😱')}>😱</span>
                    <span onClick={() => addEmoji('😨')}>😨</span>
                    <span onClick={() => addEmoji('😰')}>😰</span>
                    <span onClick={() => addEmoji('😥')}>😥</span>
                    <span onClick={() => addEmoji('😓')}>😓</span>
                    <span onClick={() => addEmoji('🫣')}>🫣</span>
                    <span onClick={() => addEmoji('🤗')}>🤗</span>
                    <span onClick={() => addEmoji('🫡')}>🫡</span>
                    <span onClick={() => addEmoji('🤔')}>🤔</span>
                    <span onClick={() => addEmoji('🫢')}>🫢</span>
                    <span onClick={() => addEmoji('🤭')}>🤭</span>
                    <span onClick={() => addEmoji('🤫')}>🤫</span>
                    <span onClick={() => addEmoji('🤥')}>🤥</span>
                    <span onClick={() => addEmoji('😶')}>😶</span>
                    <span onClick={() => addEmoji('😶')}>😶</span>
                    <span onClick={() => addEmoji('😐')}>😐</span>
                    <span onClick={() => addEmoji('😑')}>😑</span>
                    <span onClick={() => addEmoji('😬')}>😬</span>
                    <span onClick={() => addEmoji('🫨')}>🫨</span>
                    <span onClick={() => addEmoji('🫠')}>🫠</span>
                    <span onClick={() => addEmoji('🙄')}>🙄</span>
                    <span onClick={() => addEmoji('😯')}>😯</span>
                    <span onClick={() => addEmoji('😦')}>😦</span>
                    <span onClick={() => addEmoji('😧')}>😧</span>
                    <span onClick={() => addEmoji('😮')}>😮</span>
                    <span onClick={() => addEmoji('😲')}>😲</span>
                    <span onClick={() => addEmoji('🥱')}>🥱</span>
                    <span onClick={() => addEmoji('😴')}>😴</span>
                    <span onClick={() => addEmoji('🤤')}>🤤</span>
                    <span onClick={() => addEmoji('😪')}>😪</span>
                    <span onClick={() => addEmoji('😵')}>😵</span>
                    <span onClick={() => addEmoji('😵')}>😵</span>
                    <span onClick={() => addEmoji('🫥')}>🫥</span>
                    <span onClick={() => addEmoji('🤐')}>🤐</span>
                    <span onClick={() => addEmoji('🥴')}>🥴</span>
                    <span onClick={() => addEmoji('🤢')}>🤢</span>
                    <span onClick={() => addEmoji('🤮')}>🤮</span>
                    <span onClick={() => addEmoji('🤧')}>🤧</span>
                    <span onClick={() => addEmoji('😷')}>😷</span>
                    <span onClick={() => addEmoji('🤒')}>🤒</span>
                    <span onClick={() => addEmoji('🤕')}>🤕</span>
                    <span onClick={() => addEmoji('🤑')}>🤑</span>
                    <span onClick={() => addEmoji('🤠')}>🤠</span>
                    <span onClick={() => addEmoji('😈')}>😈</span>
                    <span onClick={() => addEmoji('👿')}>👿</span>
                    <span onClick={() => addEmoji('👹')}>👹</span>
                    <span onClick={() => addEmoji('👺')}>👺</span>
                    <span onClick={() => addEmoji('🤡')}>🤡</span>
                    <span onClick={() => addEmoji('💩')}>💩</span>
                    <span onClick={() => addEmoji('👻')}>👻</span>
                    <span onClick={() => addEmoji('💀')}>💀</span>
                    <span onClick={() => addEmoji('☠️')}>☠️</span>
                    <span onClick={() => addEmoji('👽')}>👽</span>
                    <span onClick={() => addEmoji('👾')}>👾</span>
                    <span onClick={() => addEmoji('🤖')}>🤖</span>
                    <span onClick={() => addEmoji('🎃')}>🎃</span>
                    <span onClick={() => addEmoji('😺')}>😺</span>
                    <span onClick={() => addEmoji('😸')}>😸</span>
                    <span onClick={() => addEmoji('😹')}>😹</span>
                    <span onClick={() => addEmoji('😻')}>😻</span>
                    <span onClick={() => addEmoji('😼')}>😼</span>
                    <span onClick={() => addEmoji('😽')}>😽</span>
                    <span onClick={() => addEmoji('🙀')}>🙀</span>
                    <span onClick={() => addEmoji('😿')}>😿</span>
                    <span onClick={() => addEmoji('😾')}>😾</span>
                    <span onClick={() => addEmoji('👋')}>👋</span>
                    <span onClick={() => addEmoji('🤚')}>🤚</span>
                    <span onClick={() => addEmoji('🖐')}>🖐</span>
                    <span onClick={() => addEmoji('✋')}>✋</span>
                    <span onClick={() => addEmoji('🖖')}>🖖</span>
                    <span onClick={() => addEmoji('👌')}>👌</span>
                    <span onClick={() => addEmoji('🤌')}>🤌</span>
                    <span onClick={() => addEmoji('🤏')}>🤏</span>
                    <span onClick={() => addEmoji('✌️')}>✌️</span>
                    <span onClick={() => addEmoji('🤞')}>🤞</span>
                    <span onClick={() => addEmoji('🫰')}>🫰</span>
                    <span onClick={() => addEmoji('🤟')}>🤟</span>
                    <span onClick={() => addEmoji('🤘')}>🤘</span>
                    <span onClick={() => addEmoji('🤙')}>🤙</span>
                    <span onClick={() => addEmoji('🫵')}>🫵</span>
                    <span onClick={() => addEmoji('🫱')}>🫱</span>
                    <span onClick={() => addEmoji('🫲')}>🫲</span>
                    <span onClick={() => addEmoji('🫸')}>🫸</span>
                    <span onClick={() => addEmoji('🫷')}>🫷</span>
                    <span onClick={() => addEmoji('🫳')}>🫳</span>
                    <span onClick={() => addEmoji('🫴')}>🫴</span>
                    <span onClick={() => addEmoji('👈')}>👈</span>
                    <span onClick={() => addEmoji('👉')}>👉</span>
                    <span onClick={() => addEmoji('👆')}>👆</span>
                    <span onClick={() => addEmoji('🖕')}>🖕</span>
                    <span onClick={() => addEmoji('👇')}>👇</span>
                    <span onClick={() => addEmoji('☝️')}>☝️</span>
                    <span onClick={() => addEmoji('👍')}>👍</span>
                    <span onClick={() => addEmoji('👎')}>👎</span>
                    <span onClick={() => addEmoji('✊')}>✊</span>
                    <span onClick={() => addEmoji('👊')}>👊</span>
                    <span onClick={() => addEmoji('🤛')}>🤛</span>
                    <span onClick={() => addEmoji('🤜')}>🤜</span>
                    <span onClick={() => addEmoji('👏')}>👏</span>
                    <span onClick={() => addEmoji('🫶')}>🫶</span>
                    <span onClick={() => addEmoji('🙌')}>🙌</span>
                    <span onClick={() => addEmoji('👐')}>👐</span>
                    <span onClick={() => addEmoji('🤲')}>🤲</span>
                    <span onClick={() => addEmoji('🤝')}>🤝</span>
                    <span onClick={() => addEmoji('🙏')}>🙏</span>
                    <span onClick={() => addEmoji('✍️')}>✍️</span>
                    <span onClick={() => addEmoji('💅')}>💅</span>
                    <span onClick={() => addEmoji('🤳')}>🤳</span>
                    <span onClick={() => addEmoji('🍏')}>🍏</span>
                    <span onClick={() => addEmoji('🍎')}>🍎</span>
                    <span onClick={() => addEmoji('🍐')}>🍐</span>
                    <span onClick={() => addEmoji('🍊')}>🍊</span>
                    <span onClick={() => addEmoji('🍋')}>🍋</span>
                    <span onClick={() => addEmoji('🍌')}>🍌</span>
                    <span onClick={() => addEmoji('🍉')}>🍉</span>
                    <span onClick={() => addEmoji('🍇')}>🍇</span>
                    <span onClick={() => addEmoji('🍓')}>🍓</span>
                    <span onClick={() => addEmoji('🫐')}>🫐</span>
                    <span onClick={() => addEmoji('🍈')}>🍈</span>
                    <span onClick={() => addEmoji('🍒')}>🍒</span>
                    <span onClick={() => addEmoji('🍑')}>🍑</span>
                    <span onClick={() => addEmoji('🥭')}>🥭</span>
                    <span onClick={() => addEmoji('🍍')}>🍍</span>
                    <span onClick={() => addEmoji('🥥')}>🥥</span>
                    <span onClick={() => addEmoji('🥝')}>🥝</span>
                    <span onClick={() => addEmoji('🍅')}>🍅</span>
                    <span onClick={() => addEmoji('🍆')}>🍆</span>
                    <span onClick={() => addEmoji('🥑')}>🥑</span>
                    <span onClick={() => addEmoji('🥦')}>🥦</span>
                    <span onClick={() => addEmoji('🫛')}>🫛</span>
                    <span onClick={() => addEmoji('🥬')}>🥬</span>
                    <span onClick={() => addEmoji('🥒')}>🥒</span>
                    <span onClick={() => addEmoji('🌶')}>🌶</span>
                    <span onClick={() => addEmoji('🫑')}>🫑</span>
                    <span onClick={() => addEmoji('🌽')}>🌽</span>
                    <span onClick={() => addEmoji('🥕')}>🥕</span>
                    <span onClick={() => addEmoji('🫒')}>🫒</span>
                    <span onClick={() => addEmoji('🧄')}>🧄</span>
                    <span onClick={() => addEmoji('🧅')}>🧅</span>
                    <span onClick={() => addEmoji('🫚')}>🫚</span>
                    <span onClick={() => addEmoji('🥔')}>🥔</span>
                    <span onClick={() => addEmoji('🍠')}>🍠</span>
                    <span onClick={() => addEmoji('🫘')}>🫘</span>
                    <span onClick={() => addEmoji('🥐')}>🥐</span>
                    <span onClick={() => addEmoji('🥯')}>🥯</span>
                    <span onClick={() => addEmoji('🍞')}>🍞</span>
                    <span onClick={() => addEmoji('🥖')}>🥖</span>
                    <span onClick={() => addEmoji('🥨')}>🥨</span>
                    <span onClick={() => addEmoji('🧀')}>🧀</span>
                    <span onClick={() => addEmoji('🥚')}>🥚</span>
                    <span onClick={() => addEmoji('🍳')}>🍳</span>
                    <span onClick={() => addEmoji('🧈')}>🧈</span>
                    <span onClick={() => addEmoji('🥞')}>🥞</span>
                    <span onClick={() => addEmoji('🧇')}>🧇</span>
                    <span onClick={() => addEmoji('🥓')}>🥓</span>
                    <span onClick={() => addEmoji('🥩')}>🥩</span>
                    <span onClick={() => addEmoji('🍗')}>🍗</span>
                    <span onClick={() => addEmoji('🍖')}>🍖</span>
                    <span onClick={() => addEmoji('🦴')}>🦴</span>
                    <span onClick={() => addEmoji('🌭')}>🌭</span>
                    <span onClick={() => addEmoji('🍔')}>🍔</span>
                    <span onClick={() => addEmoji('🍟')}>🍟</span>
                    <span onClick={() => addEmoji('🍕')}>🍕</span>
                    <span onClick={() => addEmoji('🫓')}>🫓</span>
                    <span onClick={() => addEmoji('🥪')}>🥪</span>
                    <span onClick={() => addEmoji('🥙')}>🥙</span>
                    <span onClick={() => addEmoji('🧆')}>🧆</span>
                    <span onClick={() => addEmoji('🌮')}>🌮</span>
                    <span onClick={() => addEmoji('🌯')}>🌯</span>
                    <span onClick={() => addEmoji('🫔')}>🫔</span>
                    <span onClick={() => addEmoji('🥗')}>🥗</span>
                    <span onClick={() => addEmoji('🥘')}>🥘</span>
                    <span onClick={() => addEmoji('🫕')}>🫕</span>
                    <span onClick={() => addEmoji('🥫')}>🥫</span>
                    <span onClick={() => addEmoji('🍝')}>🍝</span>
                    <span onClick={() => addEmoji('🍜')}>🍜</span>
                    <span onClick={() => addEmoji('🍲')}>🍲</span>
                    <span onClick={() => addEmoji('🍛')}>🍛</span>
                    <span onClick={() => addEmoji('🍣')}>🍣</span>
                    <span onClick={() => addEmoji('🍱')}>🍱</span>
                    <span onClick={() => addEmoji('🥟')}>🥟</span>
                    <span onClick={() => addEmoji('🦪')}>🦪</span>
                    <span onClick={() => addEmoji('🍤')}>🍤</span>
                    <span onClick={() => addEmoji('🍙')}>🍙</span>
                    <span onClick={() => addEmoji('🍚')}>🍚</span>
                    <span onClick={() => addEmoji('🍘')}>🍘</span>
                    <span onClick={() => addEmoji('🍥')}>🍥</span>
                    <span onClick={() => addEmoji('🥠')}>🥠</span>
                    <span onClick={() => addEmoji('🥮')}>🥮</span>
                    <span onClick={() => addEmoji('🍢')}>🍢</span>
                    <span onClick={() => addEmoji('🍡')}>🍡</span>
                    <span onClick={() => addEmoji('🍧')}>🍧</span>
                    <span onClick={() => addEmoji('🍨')}>🍨</span>
                    <span onClick={() => addEmoji('🍦')}>🍦</span>
                    <span onClick={() => addEmoji('🥧')}>🥧</span>
                    <span onClick={() => addEmoji('🧁')}>🧁</span>
                    <span onClick={() => addEmoji('🍰')}>🍰</span>
                    <span onClick={() => addEmoji('🎂')}>🎂</span>
                    <span onClick={() => addEmoji('🍮')}>🍮</span>
                    <span onClick={() => addEmoji('🍭')}>🍭</span>
                    <span onClick={() => addEmoji('🍬')}>🍬</span>
                    <span onClick={() => addEmoji('🍫')}>🍫</span>
                    <span onClick={() => addEmoji('🍿')}>🍿</span>
                    <span onClick={() => addEmoji('🍩')}>🍩</span>
                    <span onClick={() => addEmoji('🍪')}>🍪</span>
                    <span onClick={() => addEmoji('🌰')}>🌰</span>
                    <span onClick={() => addEmoji('🥜')}>🥜</span>
                    <span onClick={() => addEmoji('🍯')}>🍯</span>
                    <span onClick={() => addEmoji('🥛')}>🥛</span>
                    <span onClick={() => addEmoji('🍼')}>🍼</span>
                    <span onClick={() => addEmoji('🫖')}>🫖</span>
                    <span onClick={() => addEmoji('☕️')}>☕️</span>
                    <span onClick={() => addEmoji('🍵')}>🍵</span>
                    <span onClick={() => addEmoji('🧃')}>🧃</span>
                    <span onClick={() => addEmoji('🥤')}>🥤</span>
                    <span onClick={() => addEmoji('🧋')}>🧋</span>
                    <span onClick={() => addEmoji('🫙')}>🫙</span>
                    <span onClick={() => addEmoji('🍶')}>🍶</span>
                    <span onClick={() => addEmoji('🍺')}>🍺</span>
                    <span onClick={() => addEmoji('🍻')}>🍻</span>
                    <span onClick={() => addEmoji('🥂')}>🥂</span>
                    <span onClick={() => addEmoji('🍷')}>🍷</span>
                    <span onClick={() => addEmoji('🫗')}>🫗</span>
                    <span onClick={() => addEmoji('🥃')}>🥃</span>
                    <span onClick={() => addEmoji('🍸')}>🍸</span>
                    <span onClick={() => addEmoji('🍹')}>🍹</span>
                    <span onClick={() => addEmoji('🧉')}>🧉</span>
                    <span onClick={() => addEmoji('🍾')}>🍾</span>
                    <span onClick={() => addEmoji('🧊')}>🧊</span>
                    <span onClick={() => addEmoji('🥄')}>🥄</span>
                    <span onClick={() => addEmoji('🍴')}>🍴</span>
                    <span onClick={() => addEmoji('🍽')}>🍽</span>
                    <span onClick={() => addEmoji('🥣')}>🥣</span>
                    <span onClick={() => addEmoji('🥡')}>🥡</span>
                    <span onClick={() => addEmoji('🥢')}>🥢</span>
                    <span onClick={() => addEmoji('🧂')}>🧂</span>
                    <span onClick={() => addEmoji('❤️')}>❤️</span>
                    <span onClick={() => addEmoji('🩷')}>🩷</span>
                    <span onClick={() => addEmoji('🧡')}>🧡</span>
                    <span onClick={() => addEmoji('💛')}>💛</span>
                    <span onClick={() => addEmoji('💚')}>💚</span>
                    <span onClick={() => addEmoji('💙')}>💙</span>
                    <span onClick={() => addEmoji('🩵')}>🩵</span>
                    <span onClick={() => addEmoji('💜')}>💜</span>
                    <span onClick={() => addEmoji('🖤')}>🖤</span>
                    <span onClick={() => addEmoji('🩶')}>🩶</span>
                    <span onClick={() => addEmoji('🤍')}>🤍</span>
                    <span onClick={() => addEmoji('🤎')}>🤎</span>
                    <span onClick={() => addEmoji('💔')}>💔</span>
                    <span onClick={() => addEmoji('❣️')}>❣️</span>
                    <span onClick={() => addEmoji('💕')}>💕</span>
                    <span onClick={() => addEmoji('💞')}>💞</span>
                    <span onClick={() => addEmoji('💓')}>💓</span>
                    <span onClick={() => addEmoji('💗')}>💗</span>
                    <span onClick={() => addEmoji('💖')}>💖</span>
                    <span onClick={() => addEmoji('💘')}>💘</span>
                    <span onClick={() => addEmoji('💝')}>💝</span>
                    <span onClick={() => addEmoji('💟')}>💟</span>
                    <span onClick={() => addEmoji('♠️')}>♠️</span>
                    <span onClick={() => addEmoji('♣️')}>♣️</span>
                    <span onClick={() => addEmoji('♥️')}>♥️</span>
                    <span onClick={() => addEmoji('♦️')}>♦️</span>
                    <span onClick={() => addEmoji('🕐')}>🕐</span>
                    <span onClick={() => addEmoji('🕑')}>🕑</span>
                    <span onClick={() => addEmoji('🕒')}>🕒</span>
                    <span onClick={() => addEmoji('🕓')}>🕓</span>
                    <span onClick={() => addEmoji('🕔')}>🕔</span>
                    <span onClick={() => addEmoji('🕕')}>🕕</span>
                    <span onClick={() => addEmoji('🕖')}>🕖</span>
                    <span onClick={() => addEmoji('🕗')}>🕗</span>
                    <span onClick={() => addEmoji('🕘')}>🕘</span>
                    <span onClick={() => addEmoji('🕙')}>🕙</span>
                    <span onClick={() => addEmoji('🕚')}>🕚</span>
                    <span onClick={() => addEmoji('🕛')}>🕛</span>
                    <span onClick={() => addEmoji('🕜')}>🕜</span>
                    <span onClick={() => addEmoji('🕝')}>🕝</span>
                    <span onClick={() => addEmoji('🕞')}>🕞</span>
                    <span onClick={() => addEmoji('🕟')}>🕟</span>
                    <span onClick={() => addEmoji('🕠')}>🕠</span>
                    <span onClick={() => addEmoji('🕡')}>🕡</span>
                    <span onClick={() => addEmoji('🕢')}>🕢</span>
                    <span onClick={() => addEmoji('🕣')}>🕣</span>
                    <span onClick={() => addEmoji('🕤')}>🕤</span>
                    <span onClick={() => addEmoji('🕥')}>🕥</span>
                    <span onClick={() => addEmoji('🕦')}>🕦</span>
                    <span onClick={() => addEmoji('🕧')}>🕧</span>
                    <span onClick={() => addEmoji('⚽️')}>⚽️</span>
                    <span onClick={() => addEmoji('🏀')}>🏀</span>
                    <span onClick={() => addEmoji('🏈')}>🏈</span>
                    <span onClick={() => addEmoji('⚾️')}>⚾️</span>
                    <span onClick={() => addEmoji('🥎')}>🥎</span>
                    <span onClick={() => addEmoji('🎾')}>🎾</span>
                    <span onClick={() => addEmoji('🏐')}>🏐</span>
                    <span onClick={() => addEmoji('🏉')}>🏉</span>
                    <span onClick={() => addEmoji('🥏')}>🥏</span>
                    <span onClick={() => addEmoji('🎱')}>🎱</span>
                    <span onClick={() => addEmoji('🪀')}>🪀</span>
                    <span onClick={() => addEmoji('🏓')}>🏓</span>
                    <span onClick={() => addEmoji('🏸')}>🏸</span>
                    <span onClick={() => addEmoji('🏒')}>🏒</span>
                    <span onClick={() => addEmoji('🏑')}>🏑</span>
                    <span onClick={() => addEmoji('🥍')}>🥍</span>
                    <span onClick={() => addEmoji('🏏')}>🏏</span>
                    <span onClick={() => addEmoji('🪃')}>🪃</span>
                    <span onClick={() => addEmoji('🥅')}>🥅</span>
                    <span onClick={() => addEmoji('⛳️')}>⛳️</span>
                    <span onClick={() => addEmoji('🪁')}>🪁</span>
                    <span onClick={() => addEmoji('🏹')}>🏹</span>
                    <span onClick={() => addEmoji('🎣')}>🎣</span>
                    <span onClick={() => addEmoji('🤿')}>🤿</span>
                    <span onClick={() => addEmoji('🥊')}>🥊</span>
                    <span onClick={() => addEmoji('🥋')}>🥋</span>
                    <span onClick={() => addEmoji('🎽')}>🎽</span>
                    <span onClick={() => addEmoji('🛹')}>🛹</span>
                    <span onClick={() => addEmoji('🛼')}>🛼</span>
                    <span onClick={() => addEmoji('🛷')}>🛷</span>
                    <span onClick={() => addEmoji('⛸')}>⛸</span>
                    <span onClick={() => addEmoji('🥌')}>🥌</span>
                    <span onClick={() => addEmoji('🎿')}>🎿</span>
                    <span onClick={() => addEmoji('⛷')}>⛷</span>
                    <span onClick={() => addEmoji('🏂')}>🏂</span>
                    <span onClick={() => addEmoji('🪂')}>🪂</span>
                    <span onClick={() => addEmoji('🏋️')}>🏋️</span>
                    <span onClick={() => addEmoji('🤼')}>🤼</span>
                    <span onClick={() => addEmoji('🤸')}>🤸</span>
                    <span onClick={() => addEmoji('⛹️')}>⛹️</span>
                    <span onClick={() => addEmoji('🤺')}>🤺</span>
                    <span onClick={() => addEmoji('🤾')}>🤾</span>
                    <span onClick={() => addEmoji('🏌️')}>🏌️</span>
                    <span onClick={() => addEmoji('🏇')}>🏇</span>
                    <span onClick={() => addEmoji('🧘')}>🧘</span>
                    <span onClick={() => addEmoji('🏄')}>🏄</span>
                    <span onClick={() => addEmoji('🏊')}>🏊</span>
                    <span onClick={() => addEmoji('🤽')}>🤽</span>
                    <span onClick={() => addEmoji('🚣')}>🚣</span>
                    <span onClick={() => addEmoji('🧗')}>🧗</span>
                    <span onClick={() => addEmoji('🚵')}>🚵</span>
                    <span onClick={() => addEmoji('🚴')}>🚴</span>
                    <span onClick={() => addEmoji('🏆')}>🏆</span>
                    <span onClick={() => addEmoji('🥇')}>🥇</span>
                    <span onClick={() => addEmoji('🥈')}>🥈</span>
                    <span onClick={() => addEmoji('🥉')}>🥉</span>
                    <span onClick={() => addEmoji('🏅')}>🏅</span>
                    <span onClick={() => addEmoji('🎖')}>🎖</span>
                    <span onClick={() => addEmoji('🏵')}>🏵</span>
                    <span onClick={() => addEmoji('🎗')}>🎗</span>
                    <span onClick={() => addEmoji('🎫')}>🎫</span>
                    <span onClick={() => addEmoji('🎟')}>🎟</span>
                    <span onClick={() => addEmoji('🎪')}>🎪</span>
                    <span onClick={() => addEmoji('🤹')}>🤹</span>
                    <span onClick={() => addEmoji('🎭')}>🎭</span>
                    <span onClick={() => addEmoji('🩰')}>🩰</span>
                    <span onClick={() => addEmoji('🎨')}>🎨</span>
                    <span onClick={() => addEmoji('🎬')}>🎬</span>
                    <span onClick={() => addEmoji('🎤')}>🎤</span>
                    <span onClick={() => addEmoji('🎧')}>🎧</span>
                    <span onClick={() => addEmoji('🎼')}>🎼</span>
                    <span onClick={() => addEmoji('🎹')}>🎹</span>
                    <span onClick={() => addEmoji('🥁')}>🥁</span>
                    <span onClick={() => addEmoji('🪘')}>🪘</span>
                    <span onClick={() => addEmoji('🪇')}>🪇</span>
                    <span onClick={() => addEmoji('🎷')}>🎷</span>
                    <span onClick={() => addEmoji('🎺')}>🎺</span>
                    <span onClick={() => addEmoji('🪗')}>🪗</span>
                    <span onClick={() => addEmoji('🎸')}>🎸</span>
                    <span onClick={() => addEmoji('🪕')}>🪕</span>
                    <span onClick={() => addEmoji('🎻')}>🎻</span>
                    <span onClick={() => addEmoji('🪈')}>🪈</span>
                    <span onClick={() => addEmoji('🎲')}>🎲</span>
                    <span onClick={() => addEmoji('♟')}>♟</span>
                    <span onClick={() => addEmoji('🎯')}>🎯</span>
                    <span onClick={() => addEmoji('🎳')}>🎳</span>
                    <span onClick={() => addEmoji('🎮')}>🎮</span>
                    <span onClick={() => addEmoji('🎰')}>🎰</span>
                    <span onClick={() => addEmoji('🧩')}>🧩</span>
                    <span onClick={() => addEmoji('🔥')}>🔥</span>
                    <span onClick={() => addEmoji('🎉')}>🎉</span>
                    <span onClick={() => addEmoji('🚀')}>🚀</span>
                    <span onClick={() => addEmoji('🌈')}>🌈</span>
                    <span onClick={() => addEmoji('🌟')}>🌟</span>
                </div>
            )}
            <Toolbar>
                <BtnBold className={isBold ? 'active' : ''} onClick={Bold} />
                <BtnItalic className={isItalic ? 'active' : ''} onClick={Italics} />
                <button>
                    <span className="attachment">
                        <svg className="attachment" width="20" height="15" viewBox="0 0 20 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M18.2813 1.225C17.9329 0.875397 17.5189 0.598009 17.0631 0.408738C16.6073 0.219468 16.1186 0.12204 15.625 0.12204C15.1315 0.12204 14.6428 0.219468 14.187 0.408738C13.7312 0.598009 13.3172 0.875397 12.9688 1.225L13.8563 2.1125C14.089 1.87981 14.3652 1.69523 14.6692 1.56931C14.9733 1.44338 15.2991 1.37856 15.6282 1.37856C15.9572 1.37856 16.2831 1.44338 16.5871 1.56931C16.8911 1.69523 17.1674 1.87981 17.4 2.1125C17.6327 2.34518 17.8173 2.62142 17.9432 2.92544C18.0692 3.22946 18.134 3.5553 18.134 3.88437C18.134 4.21344 18.0692 4.53928 17.9432 4.8433C17.8173 5.14732 17.6327 5.42356 17.4 5.65625L12.4 10.6562C11.9309 11.1262 11.2944 11.3905 10.6304 11.3911C9.96638 11.3917 9.32935 11.1285 8.85942 10.6594C8.38949 10.1903 8.12515 9.5537 8.12457 8.8897C8.12398 8.22571 8.38719 7.58868 8.85629 7.11875L9.73754 6.23125L8.85629 5.34375L7.96879 6.23125C7.61919 6.57963 7.3418 6.99361 7.15253 7.44943C6.96326 7.90524 6.86583 8.39394 6.86583 8.8875C6.86583 9.38105 6.96326 9.86975 7.15253 10.3256C7.3418 10.7814 7.61919 11.1954 7.96879 11.5437C8.67597 12.2419 9.63134 12.6308 10.625 12.625C11.1205 12.627 11.6114 12.5309 12.0695 12.3421C12.5276 12.1533 12.9437 11.8756 13.2938 11.525L18.2938 6.525C18.9944 5.82021 19.3866 4.86616 19.3842 3.87241C19.3819 2.87866 18.9852 1.92647 18.2813 1.225Z" fill="#212529"></path><path d="M2.61879 12.5125C2.38541 12.2802 2.20022 12.0041 2.07386 11.7C1.94749 11.3959 1.88244 11.0699 1.88244 10.7406C1.88244 10.4113 1.94749 10.0853 2.07386 9.78123C2.20022 9.47715 2.38541 9.20104 2.61879 8.96875L7.61879 3.96875C7.85109 3.73537 8.1272 3.55018 8.43127 3.42381C8.73534 3.29745 9.06138 3.2324 9.39067 3.2324C9.71995 3.2324 10.046 3.29745 10.3501 3.42381C10.6541 3.55018 10.9302 3.73537 11.1625 3.96875C11.3944 4.20287 11.577 4.48116 11.6994 4.78713C11.8218 5.0931 11.8815 5.42052 11.875 5.75C11.8769 6.0805 11.8133 6.4081 11.6878 6.71385C11.5623 7.01959 11.3774 7.29742 11.1438 7.53125L9.81879 8.875L10.7063 9.7625L12.0313 8.4375C12.7366 7.73219 13.1328 6.77558 13.1328 5.77812C13.1328 4.78066 12.7366 3.82406 12.0313 3.11875C11.326 2.41344 10.3694 2.0172 9.37192 2.0172C8.37446 2.0172 7.41785 2.41344 6.71254 3.11875L1.71254 8.11875C1.362 8.46725 1.08382 8.88161 0.893994 9.33801C0.704168 9.7944 0.606445 10.2838 0.606445 10.7781C0.606445 11.2724 0.704168 11.7618 0.893994 12.2182C1.08382 12.6746 1.362 13.089 1.71254 13.4375C2.42431 14.1303 3.38185 14.5124 4.37504 14.5C5.37698 14.501 6.33862 14.1055 7.05004 13.4L6.16254 12.5125C5.93025 12.7459 5.65413 12.9311 5.35006 13.0574C5.04599 13.1838 4.71995 13.2488 4.39067 13.2488C4.06138 13.2488 3.73534 13.1838 3.43127 13.0574C3.1272 12.9311 2.85109 12.7459 2.61879 12.5125Z" fill="#212529"></path></svg>
                    </span>
                </button>
                <button>
                    <span className="emoji" onClick={toggleEmojiPicker}>
                        <svg className="emoji" values='emoji' width="16" height="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0m0 22C6.486 22 2 17.514 2 12S6.486 2 12 2s10 4.486 10 10-4.486 10-10 10"></path><path d="M8 7a2 2 0 1 0-.001 3.999A2 2 0 0 0 8 7M16 7a2 2 0 1 0-.001 3.999A2 2 0 0 0 16 7M15.232 15c-.693 1.195-1.87 2-3.349 2-1.477 0-2.655-.805-3.347-2H15m3-2H6a6 6 0 1 0 12 0"></path></svg>
                    </span>
                </button>
                {showEmoji && (
                    <div className="emoji-picker">
                        <span onClick={() => addEmoji('😀')}>😀</span>
                        <span onClick={() => addEmoji('😃')}>😃</span>
                        <span onClick={() => addEmoji('😄')}>😄</span>
                        <span onClick={() => addEmoji('😁')}>😁</span>
                        <span onClick={() => addEmoji('😆')}>😆</span>
                        <span onClick={() => addEmoji('😅')}>😅</span>
                        <span onClick={() => addEmoji('😂')}>😂</span>
                        <span onClick={() => addEmoji('🤣')}>🤣</span>
                        <span onClick={() => addEmoji('🥲')}>🥲</span>
                        <span onClick={() => addEmoji('🥹')}>🥹</span>
                        <span onClick={() => addEmoji('😉')}>😉</span>
                        <span onClick={() => addEmoji('😊')}>😊</span>
                        <span onClick={() => addEmoji('😇')}>😇</span>
                        <span onClick={() => addEmoji('🙂')}>🙂</span>
                        <span onClick={() => addEmoji('🙃')}>🙃</span>
                        <span onClick={() => addEmoji('😌')}>😌</span>
                        <span onClick={() => addEmoji('😍')}>😍</span>
                        <span onClick={() => addEmoji('🥰')}>🥰</span>
                        <span onClick={() => addEmoji('😘')}>😘</span>
                        <span onClick={() => addEmoji('😗')}>😗</span>
                        <span onClick={() => addEmoji('😙')}>😙</span>
                        <span onClick={() => addEmoji('😚')}>😚</span>
                        <span onClick={() => addEmoji('😋')}>😋</span>
                        <span onClick={() => addEmoji('😛')}>😛</span>
                        <span onClick={() => addEmoji('😝')}>😝</span>
                        <span onClick={() => addEmoji('😜')}>😜</span>
                        <span onClick={() => addEmoji('🤪')}>🤪</span>
                        <span onClick={() => addEmoji('🤨')}>🤨</span>
                        <span onClick={() => addEmoji('🧐')}>🧐</span>
                        <span onClick={() => addEmoji('🤓')}>🤓</span>
                        <span onClick={() => addEmoji('😎')}>😎</span>
                        <span onClick={() => addEmoji('🥸')}>🥸</span>
                        <span onClick={() => addEmoji('🤩')}>🤩</span>
                        <span onClick={() => addEmoji('🥳')}>🥳</span>
                        <span onClick={() => addEmoji('🙂')}>🙂</span>
                        <span onClick={() => addEmoji('😏')}>😏</span>
                        <span onClick={() => addEmoji('😒')}>😒</span>
                        <span onClick={() => addEmoji('🙂')}>🙂</span>
                        <span onClick={() => addEmoji('😞')}>😞</span>
                        <span onClick={() => addEmoji('😔')}>😔</span>
                        <span onClick={() => addEmoji('😟')}>😟</span>
                        <span onClick={() => addEmoji('😕')}>😕</span>
                        <span onClick={() => addEmoji('🙁')}>🙁</span>
                        <span onClick={() => addEmoji('☹️')}>☹️</span>
                        <span onClick={() => addEmoji('😣')}>😣</span>
                        <span onClick={() => addEmoji('😖')}>😖</span>
                        <span onClick={() => addEmoji('😫')}>😫</span>
                        <span onClick={() => addEmoji('😩')}>😩</span>
                        <span onClick={() => addEmoji('🥺')}>🥺</span>
                        <span onClick={() => addEmoji('😢')}>😢</span>
                        <span onClick={() => addEmoji('😭')}>😭</span>
                        <span onClick={() => addEmoji('😮')}>😮</span>
                        <span onClick={() => addEmoji('😤')}>😤</span>
                        <span onClick={() => addEmoji('😠')}>😠</span>
                        <span onClick={() => addEmoji('😡')}>😡</span>
                        <span onClick={() => addEmoji('🤬')}>🤬</span>
                        <span onClick={() => addEmoji('🤯')}>🤯</span>
                        <span onClick={() => addEmoji('😳')}>😳</span>
                        <span onClick={() => addEmoji('🥵')}>🥵</span>
                        <span onClick={() => addEmoji('🥶')}>🥶</span>
                        <span onClick={() => addEmoji('😱')}>😱</span>
                        <span onClick={() => addEmoji('😨')}>😨</span>
                        <span onClick={() => addEmoji('😰')}>😰</span>
                        <span onClick={() => addEmoji('😥')}>😥</span>
                        <span onClick={() => addEmoji('😓')}>😓</span>
                        <span onClick={() => addEmoji('🫣')}>🫣</span>
                        <span onClick={() => addEmoji('🤗')}>🤗</span>
                        <span onClick={() => addEmoji('🫡')}>🫡</span>
                        <span onClick={() => addEmoji('🤔')}>🤔</span>
                        <span onClick={() => addEmoji('🫢')}>🫢</span>
                        <span onClick={() => addEmoji('🤭')}>🤭</span>
                        <span onClick={() => addEmoji('🤫')}>🤫</span>
                        <span onClick={() => addEmoji('🤥')}>🤥</span>
                        <span onClick={() => addEmoji('😶')}>😶</span>
                        <span onClick={() => addEmoji('😶')}>😶</span>
                        <span onClick={() => addEmoji('😐')}>😐</span>
                        <span onClick={() => addEmoji('😑')}>😑</span>
                        <span onClick={() => addEmoji('😬')}>😬</span>
                        <span onClick={() => addEmoji('🫨')}>🫨</span>
                        <span onClick={() => addEmoji('🫠')}>🫠</span>
                        <span onClick={() => addEmoji('🙄')}>🙄</span>
                        <span onClick={() => addEmoji('😯')}>😯</span>
                        <span onClick={() => addEmoji('😦')}>😦</span>
                        <span onClick={() => addEmoji('😧')}>😧</span>
                        <span onClick={() => addEmoji('😮')}>😮</span>
                        <span onClick={() => addEmoji('😲')}>😲</span>
                        <span onClick={() => addEmoji('🥱')}>🥱</span>
                        <span onClick={() => addEmoji('😴')}>😴</span>
                        <span onClick={() => addEmoji('🤤')}>🤤</span>
                        <span onClick={() => addEmoji('😪')}>😪</span>
                        <span onClick={() => addEmoji('😵')}>😵</span>
                        <span onClick={() => addEmoji('😵')}>😵</span>
                        <span onClick={() => addEmoji('🫥')}>🫥</span>
                        <span onClick={() => addEmoji('🤐')}>🤐</span>
                        <span onClick={() => addEmoji('🥴')}>🥴</span>
                        <span onClick={() => addEmoji('🤢')}>🤢</span>
                        <span onClick={() => addEmoji('🤮')}>🤮</span>
                        <span onClick={() => addEmoji('🤧')}>🤧</span>
                        <span onClick={() => addEmoji('😷')}>😷</span>
                        <span onClick={() => addEmoji('🤒')}>🤒</span>
                        <span onClick={() => addEmoji('🤕')}>🤕</span>
                        <span onClick={() => addEmoji('🤑')}>🤑</span>
                        <span onClick={() => addEmoji('🤠')}>🤠</span>
                        <span onClick={() => addEmoji('😈')}>😈</span>
                        <span onClick={() => addEmoji('👿')}>👿</span>
                        <span onClick={() => addEmoji('👹')}>👹</span>
                        <span onClick={() => addEmoji('👺')}>👺</span>
                        <span onClick={() => addEmoji('🤡')}>🤡</span>
                        <span onClick={() => addEmoji('💩')}>💩</span>
                        <span onClick={() => addEmoji('👻')}>👻</span>
                        <span onClick={() => addEmoji('💀')}>💀</span>
                        <span onClick={() => addEmoji('☠️')}>☠️</span>
                        <span onClick={() => addEmoji('👽')}>👽</span>
                        <span onClick={() => addEmoji('👾')}>👾</span>
                        <span onClick={() => addEmoji('🤖')}>🤖</span>
                        <span onClick={() => addEmoji('🎃')}>🎃</span>
                        <span onClick={() => addEmoji('😺')}>😺</span>
                        <span onClick={() => addEmoji('😸')}>😸</span>
                        <span onClick={() => addEmoji('😹')}>😹</span>
                        <span onClick={() => addEmoji('😻')}>😻</span>
                        <span onClick={() => addEmoji('😼')}>😼</span>
                        <span onClick={() => addEmoji('😽')}>😽</span>
                        <span onClick={() => addEmoji('🙀')}>🙀</span>
                        <span onClick={() => addEmoji('😿')}>😿</span>
                        <span onClick={() => addEmoji('😾')}>😾</span>
                        <span onClick={() => addEmoji('👋')}>👋</span>
                        <span onClick={() => addEmoji('🤚')}>🤚</span>
                        <span onClick={() => addEmoji('🖐')}>🖐</span>
                        <span onClick={() => addEmoji('✋')}>✋</span>
                        <span onClick={() => addEmoji('🖖')}>🖖</span>
                        <span onClick={() => addEmoji('👌')}>👌</span>
                        <span onClick={() => addEmoji('🤌')}>🤌</span>
                        <span onClick={() => addEmoji('🤏')}>🤏</span>
                        <span onClick={() => addEmoji('✌️')}>✌️</span>
                        <span onClick={() => addEmoji('🤞')}>🤞</span>
                        <span onClick={() => addEmoji('🫰')}>🫰</span>
                        <span onClick={() => addEmoji('🤟')}>🤟</span>
                        <span onClick={() => addEmoji('🤘')}>🤘</span>
                        <span onClick={() => addEmoji('🤙')}>🤙</span>
                        <span onClick={() => addEmoji('🫵')}>🫵</span>
                        <span onClick={() => addEmoji('🫱')}>🫱</span>
                        <span onClick={() => addEmoji('🫲')}>🫲</span>
                        <span onClick={() => addEmoji('🫸')}>🫸</span>
                        <span onClick={() => addEmoji('🫷')}>🫷</span>
                        <span onClick={() => addEmoji('🫳')}>🫳</span>
                        <span onClick={() => addEmoji('🫴')}>🫴</span>
                        <span onClick={() => addEmoji('👈')}>👈</span>
                        <span onClick={() => addEmoji('👉')}>👉</span>
                        <span onClick={() => addEmoji('👆')}>👆</span>
                        <span onClick={() => addEmoji('🖕')}>🖕</span>
                        <span onClick={() => addEmoji('👇')}>👇</span>
                        <span onClick={() => addEmoji('☝️')}>☝️</span>
                        <span onClick={() => addEmoji('👍')}>👍</span>
                        <span onClick={() => addEmoji('👎')}>👎</span>
                        <span onClick={() => addEmoji('✊')}>✊</span>
                        <span onClick={() => addEmoji('👊')}>👊</span>
                        <span onClick={() => addEmoji('🤛')}>🤛</span>
                        <span onClick={() => addEmoji('🤜')}>🤜</span>
                        <span onClick={() => addEmoji('👏')}>👏</span>
                        <span onClick={() => addEmoji('🫶')}>🫶</span>
                        <span onClick={() => addEmoji('🙌')}>🙌</span>
                        <span onClick={() => addEmoji('👐')}>👐</span>
                        <span onClick={() => addEmoji('🤲')}>🤲</span>
                        <span onClick={() => addEmoji('🤝')}>🤝</span>
                        <span onClick={() => addEmoji('🙏')}>🙏</span>
                        <span onClick={() => addEmoji('✍️')}>✍️</span>
                        <span onClick={() => addEmoji('💅')}>💅</span>
                        <span onClick={() => addEmoji('🤳')}>🤳</span>
                        <span onClick={() => addEmoji('🍏')}>🍏</span>
                        <span onClick={() => addEmoji('🍎')}>🍎</span>
                        <span onClick={() => addEmoji('🍐')}>🍐</span>
                        <span onClick={() => addEmoji('🍊')}>🍊</span>
                        <span onClick={() => addEmoji('🍋')}>🍋</span>
                        <span onClick={() => addEmoji('🍌')}>🍌</span>
                        <span onClick={() => addEmoji('🍉')}>🍉</span>
                        <span onClick={() => addEmoji('🍇')}>🍇</span>
                        <span onClick={() => addEmoji('🍓')}>🍓</span>
                        <span onClick={() => addEmoji('🫐')}>🫐</span>
                        <span onClick={() => addEmoji('🍈')}>🍈</span>
                        <span onClick={() => addEmoji('🍒')}>🍒</span>
                        <span onClick={() => addEmoji('🍑')}>🍑</span>
                        <span onClick={() => addEmoji('🥭')}>🥭</span>
                        <span onClick={() => addEmoji('🍍')}>🍍</span>
                        <span onClick={() => addEmoji('🥥')}>🥥</span>
                        <span onClick={() => addEmoji('🥝')}>🥝</span>
                        <span onClick={() => addEmoji('🍅')}>🍅</span>
                        <span onClick={() => addEmoji('🍆')}>🍆</span>
                        <span onClick={() => addEmoji('🥑')}>🥑</span>
                        <span onClick={() => addEmoji('🥦')}>🥦</span>
                        <span onClick={() => addEmoji('🫛')}>🫛</span>
                        <span onClick={() => addEmoji('🥬')}>🥬</span>
                        <span onClick={() => addEmoji('🥒')}>🥒</span>
                        <span onClick={() => addEmoji('🌶')}>🌶</span>
                        <span onClick={() => addEmoji('🫑')}>🫑</span>
                        <span onClick={() => addEmoji('🌽')}>🌽</span>
                        <span onClick={() => addEmoji('🥕')}>🥕</span>
                        <span onClick={() => addEmoji('🫒')}>🫒</span>
                        <span onClick={() => addEmoji('🧄')}>🧄</span>
                        <span onClick={() => addEmoji('🧅')}>🧅</span>
                        <span onClick={() => addEmoji('🫚')}>🫚</span>
                        <span onClick={() => addEmoji('🥔')}>🥔</span>
                        <span onClick={() => addEmoji('🍠')}>🍠</span>
                        <span onClick={() => addEmoji('🫘')}>🫘</span>
                        <span onClick={() => addEmoji('🥐')}>🥐</span>
                        <span onClick={() => addEmoji('🥯')}>🥯</span>
                        <span onClick={() => addEmoji('🍞')}>🍞</span>
                        <span onClick={() => addEmoji('🥖')}>🥖</span>
                        <span onClick={() => addEmoji('🥨')}>🥨</span>
                        <span onClick={() => addEmoji('🧀')}>🧀</span>
                        <span onClick={() => addEmoji('🥚')}>🥚</span>
                        <span onClick={() => addEmoji('🍳')}>🍳</span>
                        <span onClick={() => addEmoji('🧈')}>🧈</span>
                        <span onClick={() => addEmoji('🥞')}>🥞</span>
                        <span onClick={() => addEmoji('🧇')}>🧇</span>
                        <span onClick={() => addEmoji('🥓')}>🥓</span>
                        <span onClick={() => addEmoji('🥩')}>🥩</span>
                        <span onClick={() => addEmoji('🍗')}>🍗</span>
                        <span onClick={() => addEmoji('🍖')}>🍖</span>
                        <span onClick={() => addEmoji('🦴')}>🦴</span>
                        <span onClick={() => addEmoji('🌭')}>🌭</span>
                        <span onClick={() => addEmoji('🍔')}>🍔</span>
                        <span onClick={() => addEmoji('🍟')}>🍟</span>
                        <span onClick={() => addEmoji('🍕')}>🍕</span>
                        <span onClick={() => addEmoji('🫓')}>🫓</span>
                        <span onClick={() => addEmoji('🥪')}>🥪</span>
                        <span onClick={() => addEmoji('🥙')}>🥙</span>
                        <span onClick={() => addEmoji('🧆')}>🧆</span>
                        <span onClick={() => addEmoji('🌮')}>🌮</span>
                        <span onClick={() => addEmoji('🌯')}>🌯</span>
                        <span onClick={() => addEmoji('🫔')}>🫔</span>
                        <span onClick={() => addEmoji('🥗')}>🥗</span>
                        <span onClick={() => addEmoji('🥘')}>🥘</span>
                        <span onClick={() => addEmoji('🫕')}>🫕</span>
                        <span onClick={() => addEmoji('🥫')}>🥫</span>
                        <span onClick={() => addEmoji('🍝')}>🍝</span>
                        <span onClick={() => addEmoji('🍜')}>🍜</span>
                        <span onClick={() => addEmoji('🍲')}>🍲</span>
                        <span onClick={() => addEmoji('🍛')}>🍛</span>
                        <span onClick={() => addEmoji('🍣')}>🍣</span>
                        <span onClick={() => addEmoji('🍱')}>🍱</span>
                        <span onClick={() => addEmoji('🥟')}>🥟</span>
                        <span onClick={() => addEmoji('🦪')}>🦪</span>
                        <span onClick={() => addEmoji('🍤')}>🍤</span>
                        <span onClick={() => addEmoji('🍙')}>🍙</span>
                        <span onClick={() => addEmoji('🍚')}>🍚</span>
                        <span onClick={() => addEmoji('🍘')}>🍘</span>
                        <span onClick={() => addEmoji('🍥')}>🍥</span>
                        <span onClick={() => addEmoji('🥠')}>🥠</span>
                        <span onClick={() => addEmoji('🥮')}>🥮</span>
                        <span onClick={() => addEmoji('🍢')}>🍢</span>
                        <span onClick={() => addEmoji('🍡')}>🍡</span>
                        <span onClick={() => addEmoji('🍧')}>🍧</span>
                        <span onClick={() => addEmoji('🍨')}>🍨</span>
                        <span onClick={() => addEmoji('🍦')}>🍦</span>
                        <span onClick={() => addEmoji('🥧')}>🥧</span>
                        <span onClick={() => addEmoji('🧁')}>🧁</span>
                        <span onClick={() => addEmoji('🍰')}>🍰</span>
                        <span onClick={() => addEmoji('🎂')}>🎂</span>
                        <span onClick={() => addEmoji('🍮')}>🍮</span>
                        <span onClick={() => addEmoji('🍭')}>🍭</span>
                        <span onClick={() => addEmoji('🍬')}>🍬</span>
                        <span onClick={() => addEmoji('🍫')}>🍫</span>
                        <span onClick={() => addEmoji('🍿')}>🍿</span>
                        <span onClick={() => addEmoji('🍩')}>🍩</span>
                        <span onClick={() => addEmoji('🍪')}>🍪</span>
                        <span onClick={() => addEmoji('🌰')}>🌰</span>
                        <span onClick={() => addEmoji('🥜')}>🥜</span>
                        <span onClick={() => addEmoji('🍯')}>🍯</span>
                        <span onClick={() => addEmoji('🥛')}>🥛</span>
                        <span onClick={() => addEmoji('🍼')}>🍼</span>
                        <span onClick={() => addEmoji('🫖')}>🫖</span>
                        <span onClick={() => addEmoji('☕️')}>☕️</span>
                        <span onClick={() => addEmoji('🍵')}>🍵</span>
                        <span onClick={() => addEmoji('🧃')}>🧃</span>
                        <span onClick={() => addEmoji('🥤')}>🥤</span>
                        <span onClick={() => addEmoji('🧋')}>🧋</span>
                        <span onClick={() => addEmoji('🫙')}>🫙</span>
                        <span onClick={() => addEmoji('🍶')}>🍶</span>
                        <span onClick={() => addEmoji('🍺')}>🍺</span>
                        <span onClick={() => addEmoji('🍻')}>🍻</span>
                        <span onClick={() => addEmoji('🥂')}>🥂</span>
                        <span onClick={() => addEmoji('🍷')}>🍷</span>
                        <span onClick={() => addEmoji('🫗')}>🫗</span>
                        <span onClick={() => addEmoji('🥃')}>🥃</span>
                        <span onClick={() => addEmoji('🍸')}>🍸</span>
                        <span onClick={() => addEmoji('🍹')}>🍹</span>
                        <span onClick={() => addEmoji('🧉')}>🧉</span>
                        <span onClick={() => addEmoji('🍾')}>🍾</span>
                        <span onClick={() => addEmoji('🧊')}>🧊</span>
                        <span onClick={() => addEmoji('🥄')}>🥄</span>
                        <span onClick={() => addEmoji('🍴')}>🍴</span>
                        <span onClick={() => addEmoji('🍽')}>🍽</span>
                        <span onClick={() => addEmoji('🥣')}>🥣</span>
                        <span onClick={() => addEmoji('🥡')}>🥡</span>
                        <span onClick={() => addEmoji('🥢')}>🥢</span>
                        <span onClick={() => addEmoji('🧂')}>🧂</span>
                        <span onClick={() => addEmoji('❤️')}>❤️</span>
                        <span onClick={() => addEmoji('🩷')}>🩷</span>
                        <span onClick={() => addEmoji('🧡')}>🧡</span>
                        <span onClick={() => addEmoji('💛')}>💛</span>
                        <span onClick={() => addEmoji('💚')}>💚</span>
                        <span onClick={() => addEmoji('💙')}>💙</span>
                        <span onClick={() => addEmoji('🩵')}>🩵</span>
                        <span onClick={() => addEmoji('💜')}>💜</span>
                        <span onClick={() => addEmoji('🖤')}>🖤</span>
                        <span onClick={() => addEmoji('🩶')}>🩶</span>
                        <span onClick={() => addEmoji('🤍')}>🤍</span>
                        <span onClick={() => addEmoji('🤎')}>🤎</span>
                        <span onClick={() => addEmoji('💔')}>💔</span>
                        <span onClick={() => addEmoji('❣️')}>❣️</span>
                        <span onClick={() => addEmoji('💕')}>💕</span>
                        <span onClick={() => addEmoji('💞')}>💞</span>
                        <span onClick={() => addEmoji('💓')}>💓</span>
                        <span onClick={() => addEmoji('💗')}>💗</span>
                        <span onClick={() => addEmoji('💖')}>💖</span>
                        <span onClick={() => addEmoji('💘')}>💘</span>
                        <span onClick={() => addEmoji('💝')}>💝</span>
                        <span onClick={() => addEmoji('💟')}>💟</span>
                        <span onClick={() => addEmoji('♠️')}>♠️</span>
                        <span onClick={() => addEmoji('♣️')}>♣️</span>
                        <span onClick={() => addEmoji('♥️')}>♥️</span>
                        <span onClick={() => addEmoji('♦️')}>♦️</span>
                        <span onClick={() => addEmoji('🕐')}>🕐</span>
                        <span onClick={() => addEmoji('🕑')}>🕑</span>
                        <span onClick={() => addEmoji('🕒')}>🕒</span>
                        <span onClick={() => addEmoji('🕓')}>🕓</span>
                        <span onClick={() => addEmoji('🕔')}>🕔</span>
                        <span onClick={() => addEmoji('🕕')}>🕕</span>
                        <span onClick={() => addEmoji('🕖')}>🕖</span>
                        <span onClick={() => addEmoji('🕗')}>🕗</span>
                        <span onClick={() => addEmoji('🕘')}>🕘</span>
                        <span onClick={() => addEmoji('🕙')}>🕙</span>
                        <span onClick={() => addEmoji('🕚')}>🕚</span>
                        <span onClick={() => addEmoji('🕛')}>🕛</span>
                        <span onClick={() => addEmoji('🕜')}>🕜</span>
                        <span onClick={() => addEmoji('🕝')}>🕝</span>
                        <span onClick={() => addEmoji('🕞')}>🕞</span>
                        <span onClick={() => addEmoji('🕟')}>🕟</span>
                        <span onClick={() => addEmoji('🕠')}>🕠</span>
                        <span onClick={() => addEmoji('🕡')}>🕡</span>
                        <span onClick={() => addEmoji('🕢')}>🕢</span>
                        <span onClick={() => addEmoji('🕣')}>🕣</span>
                        <span onClick={() => addEmoji('🕤')}>🕤</span>
                        <span onClick={() => addEmoji('🕥')}>🕥</span>
                        <span onClick={() => addEmoji('🕦')}>🕦</span>
                        <span onClick={() => addEmoji('🕧')}>🕧</span>
                        <span onClick={() => addEmoji('⚽️')}>⚽️</span>
                        <span onClick={() => addEmoji('🏀')}>🏀</span>
                        <span onClick={() => addEmoji('🏈')}>🏈</span>
                        <span onClick={() => addEmoji('⚾️')}>⚾️</span>
                        <span onClick={() => addEmoji('🥎')}>🥎</span>
                        <span onClick={() => addEmoji('🎾')}>🎾</span>
                        <span onClick={() => addEmoji('🏐')}>🏐</span>
                        <span onClick={() => addEmoji('🏉')}>🏉</span>
                        <span onClick={() => addEmoji('🥏')}>🥏</span>
                        <span onClick={() => addEmoji('🎱')}>🎱</span>
                        <span onClick={() => addEmoji('🪀')}>🪀</span>
                        <span onClick={() => addEmoji('🏓')}>🏓</span>
                        <span onClick={() => addEmoji('🏸')}>🏸</span>
                        <span onClick={() => addEmoji('🏒')}>🏒</span>
                        <span onClick={() => addEmoji('🏑')}>🏑</span>
                        <span onClick={() => addEmoji('🥍')}>🥍</span>
                        <span onClick={() => addEmoji('🏏')}>🏏</span>
                        <span onClick={() => addEmoji('🪃')}>🪃</span>
                        <span onClick={() => addEmoji('🥅')}>🥅</span>
                        <span onClick={() => addEmoji('⛳️')}>⛳️</span>
                        <span onClick={() => addEmoji('🪁')}>🪁</span>
                        <span onClick={() => addEmoji('🏹')}>🏹</span>
                        <span onClick={() => addEmoji('🎣')}>🎣</span>
                        <span onClick={() => addEmoji('🤿')}>🤿</span>
                        <span onClick={() => addEmoji('🥊')}>🥊</span>
                        <span onClick={() => addEmoji('🥋')}>🥋</span>
                        <span onClick={() => addEmoji('🎽')}>🎽</span>
                        <span onClick={() => addEmoji('🛹')}>🛹</span>
                        <span onClick={() => addEmoji('🛼')}>🛼</span>
                        <span onClick={() => addEmoji('🛷')}>🛷</span>
                        <span onClick={() => addEmoji('⛸')}>⛸</span>
                        <span onClick={() => addEmoji('🥌')}>🥌</span>
                        <span onClick={() => addEmoji('🎿')}>🎿</span>
                        <span onClick={() => addEmoji('⛷')}>⛷</span>
                        <span onClick={() => addEmoji('🏂')}>🏂</span>
                        <span onClick={() => addEmoji('🪂')}>🪂</span>
                        <span onClick={() => addEmoji('🏋️')}>🏋️</span>
                        <span onClick={() => addEmoji('🤼')}>🤼</span>
                        <span onClick={() => addEmoji('🤸')}>🤸</span>
                        <span onClick={() => addEmoji('⛹️')}>⛹️</span>
                        <span onClick={() => addEmoji('🤺')}>🤺</span>
                        <span onClick={() => addEmoji('🤾')}>🤾</span>
                        <span onClick={() => addEmoji('🏌️')}>🏌️</span>
                        <span onClick={() => addEmoji('🏇')}>🏇</span>
                        <span onClick={() => addEmoji('🧘')}>🧘</span>
                        <span onClick={() => addEmoji('🏄')}>🏄</span>
                        <span onClick={() => addEmoji('🏊')}>🏊</span>
                        <span onClick={() => addEmoji('🤽')}>🤽</span>
                        <span onClick={() => addEmoji('🚣')}>🚣</span>
                        <span onClick={() => addEmoji('🧗')}>🧗</span>
                        <span onClick={() => addEmoji('🚵')}>🚵</span>
                        <span onClick={() => addEmoji('🚴')}>🚴</span>
                        <span onClick={() => addEmoji('🏆')}>🏆</span>
                        <span onClick={() => addEmoji('🥇')}>🥇</span>
                        <span onClick={() => addEmoji('🥈')}>🥈</span>
                        <span onClick={() => addEmoji('🥉')}>🥉</span>
                        <span onClick={() => addEmoji('🏅')}>🏅</span>
                        <span onClick={() => addEmoji('🎖')}>🎖</span>
                        <span onClick={() => addEmoji('🏵')}>🏵</span>
                        <span onClick={() => addEmoji('🎗')}>🎗</span>
                        <span onClick={() => addEmoji('🎫')}>🎫</span>
                        <span onClick={() => addEmoji('🎟')}>🎟</span>
                        <span onClick={() => addEmoji('🎪')}>🎪</span>
                        <span onClick={() => addEmoji('🤹')}>🤹</span>
                        <span onClick={() => addEmoji('🎭')}>🎭</span>
                        <span onClick={() => addEmoji('🩰')}>🩰</span>
                        <span onClick={() => addEmoji('🎨')}>🎨</span>
                        <span onClick={() => addEmoji('🎬')}>🎬</span>
                        <span onClick={() => addEmoji('🎤')}>🎤</span>
                        <span onClick={() => addEmoji('🎧')}>🎧</span>
                        <span onClick={() => addEmoji('🎼')}>🎼</span>
                        <span onClick={() => addEmoji('🎹')}>🎹</span>
                        <span onClick={() => addEmoji('🥁')}>🥁</span>
                        <span onClick={() => addEmoji('🪘')}>🪘</span>
                        <span onClick={() => addEmoji('🪇')}>🪇</span>
                        <span onClick={() => addEmoji('🎷')}>🎷</span>
                        <span onClick={() => addEmoji('🎺')}>🎺</span>
                        <span onClick={() => addEmoji('🪗')}>🪗</span>
                        <span onClick={() => addEmoji('🎸')}>🎸</span>
                        <span onClick={() => addEmoji('🪕')}>🪕</span>
                        <span onClick={() => addEmoji('🎻')}>🎻</span>
                        <span onClick={() => addEmoji('🪈')}>🪈</span>
                        <span onClick={() => addEmoji('🎲')}>🎲</span>
                        <span onClick={() => addEmoji('♟')}>♟</span>
                        <span onClick={() => addEmoji('🎯')}>🎯</span>
                        <span onClick={() => addEmoji('🎳')}>🎳</span>
                        <span onClick={() => addEmoji('🎮')}>🎮</span>
                        <span onClick={() => addEmoji('🎰')}>🎰</span>
                        <span onClick={() => addEmoji('🧩')}>🧩</span>
                        <span onClick={() => addEmoji('🔥')}>🔥</span>
                        <span onClick={() => addEmoji('🎉')}>🎉</span>
                        <span onClick={() => addEmoji('🚀')}>🚀</span>
                        <span onClick={() => addEmoji('🌈')}>🌈</span>
                        <span onClick={() => addEmoji('🌟')}>🌟</span>
                    </div>
                )}
            </Toolbar>
        </div>
        <div>
            <Editor style={{ border: 'none', direction: 'rtl' }} id='textbox' className='textarea' value={text} placeholder={text.length > 0 ? text : "Your text"} onChange={handleTextAreaChange} />
            <textarea value={text} placeholder={text.length > 0 ? text : "Your text"} onChange={handleTextAreaChange} id='textbox' className='textarea'></textarea>
        </div>
    </div>
</EditorProvider>  */}

const handleInputCategoryChange = (event) => {
    document.getElementById("cate-name").textContent = event.target.value || "Electronics";
  }

<div className="category-header" id='category-header'>
    <p className="text-sm font-bold tracking-wide"><b>Add Categories</b></p>
    <div className="outer-container">
        <div className="pic-input">
            <label tabIndex="0" className="pic">
                <span className="sr-only" hidden>
                    Upload Logo
                </span>
                {/* SVG icon (only visible when no image is uploaded) */}
                {/* {!icon && ( */}
                <svg className="" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M20.97 1H18.03C17.16 1 16.52 1.36 16.23 2C16.07 2.29 16 2.63 16 3.03V5.97C16 7.24 16.76 8 18.03 8H20.97C21.37 8 21.71 7.93 22 7.77C22.64 7.48 23 6.84 23 5.97V3.03C23 1.76 22.24 1 20.97 1ZM21.91 4.93C21.81 5.03 21.66 5.1 21.5 5.11H20.09V5.62L20.1 6.5C20.09 6.67 20.03 6.81 19.91 6.93C19.81 7.03 19.66 7.1 19.5 7.1C19.17 7.1 18.9 6.83 18.9 6.5V5.1L17.5 5.11C17.17 5.11 16.9 4.83 16.9 4.5C16.9 4.17 17.17 3.9 17.5 3.9L18.38 3.91H18.9V2.51C18.9 2.18 19.17 1.9 19.5 1.9C19.83 1.9 20.1 2.18 20.1 2.51L20.09 3.22V3.9H21.5C21.83 3.9 22.1 4.17 22.1 4.5C22.09 4.67 22.02 4.81 21.91 4.93Z" fill="#25D366" ></path>
                    <path fillRule="evenodd" clipRule="evenodd" d="M15 3.75H3.75C3.15326 3.75 2.58097 3.98705 2.15901 4.40901C1.73705 4.83097 1.5 5.40326 1.5 6V15.75V18C1.5 18.5967 1.73705 19.169 2.15901 19.591C2.58097 20.0129 3.15326 20.25 3.75 20.25H20.25C20.8467 20.25 21.419 20.0129 21.841 19.591C22.2629 19.169 22.5 18.5967 22.5 18V15.75V8.80701C22.1765 8.9403 21.8089 9 21.39 9H21V13.9393L19.3713 12.3107C19.0928 12.0321 18.762 11.8111 18.3981 11.6603C18.0341 11.5096 17.644 11.432 17.25 11.432C16.856 11.432 16.4659 11.5096 16.1019 11.6603C15.738 11.8111 15.4072 12.0321 15.1287 12.3107L14.25 13.1893L11.1213 10.0607C10.8428 9.78209 10.512 9.56111 10.1481 9.41035C9.78408 9.25958 9.39397 9.18198 9 9.18198C8.60603 9.18198 8.21592 9.25958 7.85194 9.41035C7.48796 9.56111 7.15725 9.78209 6.87867 10.0607L6.87867 10.0607L3 13.9393V6C3 5.80109 3.07902 5.61032 3.21967 5.46967C3.36032 5.32902 3.55109 5.25 3.75 5.25H15V3.75ZM3 18V16.0607L7.93933 11.1213L7.93933 11.1213C8.07862 10.982 8.24398 10.8715 8.42597 10.7962C8.60796 10.7208 8.80302 10.682 9 10.682C9.19698 10.682 9.39204 10.7208 9.57403 10.7962C9.75602 10.8715 9.92138 10.982 10.0607 11.1213L13.7197 14.7803L15.2197 16.2803C15.5126 16.5732 15.9874 16.5732 16.2803 16.2803C16.5732 15.9874 16.5732 15.5126 16.2803 15.2197L15.3107 14.25L16.1893 13.3713L15.6773 12.8593L16.1893 13.3713C16.3286 13.232 16.494 13.1215 16.676 13.0462C16.858 12.9708 17.053 12.932 17.25 12.932C17.447 12.932 17.642 12.9708 17.824 13.0462C18.006 13.1215 18.1714 13.232 18.3107 13.3713L21 16.0607V18C21 18.1989 20.921 18.3897 20.7803 18.5303C20.6397 18.671 20.4489 18.75 20.25 18.75H3.75C3.55109 18.75 3.36032 18.671 3.21967 18.5303C3.07902 18.3897 3 18.1989 3 18ZM14.25 7.125C13.9516 7.125 13.6655 7.24353 13.4545 7.4545C13.2435 7.66548 13.125 7.95163 13.125 8.25C13.125 8.54837 13.2435 8.83452 13.4545 9.0455C13.6655 9.25648 13.9516 9.375 14.25 9.375C14.5484 9.375 14.8345 9.25648 15.0455 9.0455C15.2565 8.83452 15.375 8.54837 15.375 8.25C15.375 7.95163 15.2565 7.66548 15.0455 7.4545C14.8345 7.24353 14.5484 7.125 14.25 7.125Z" fill="#25D366"></path>
                </svg>
                {/* )} */}
                <div className="image-upload-container">
                    <input type="file" accept="image/*" className="" hidden />

                    <div className="image-container">
                        {/* Display the uploaded image and close button if an image is uploaded */}
                        {/* {icon && (
        <>
          <button type="button" className="btn-close" aria-label="Close" onClick={handleRemoveImage}></button>
          <img src={icon} alt="Uploaded" className="uploaded-image" />
        </>
      )} */}
                    </div>
                </div>
            </label>
            <input type="text" placeholder="Customer Name" onInput={handleInputCategoryChange} />
        </div>
        <div className="tip">
            <span className="tiptext">Enter all the categories that you want to show</span>
            <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M5.85638 6.5C6.31398 5.52901 7.54869 4.83333 9.00004 4.83333C10.841 4.83333 12.3334 5.95262 12.3334 7.33333C12.3334 8.49953 11.2687 9.47923 9.82856 9.7555C9.37657 9.84221 9.00004 10.2064 9.00004 10.6667M9 13.1667H9.00833M16.5 9C16.5 13.1421 13.1421 16.5 9 16.5C4.85786 16.5 1.5 13.1421 1.5 9C1.5 4.85786 4.85786 1.5 9 1.5C13.1421 1.5 16.5 4.85786 16.5 9Z" stroke="#D4D4D8" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"></path></svg>
        </div>
    </div>
</div>